// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The response message containing the greetings
type ExposedServicesMessages struct {
	Name                 string                                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExposedServices      []*ExposedServicesMessages_ExposedService `protobuf:"bytes,2,rep,name=ExposedServices,proto3" json:"ExposedServices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *ExposedServicesMessages) Reset()         { *m = ExposedServicesMessages{} }
func (m *ExposedServicesMessages) String() string { return proto.CompactTextString(m) }
func (*ExposedServicesMessages) ProtoMessage()    {}
func (*ExposedServicesMessages) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{0}
}

func (m *ExposedServicesMessages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExposedServicesMessages.Unmarshal(m, b)
}
func (m *ExposedServicesMessages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExposedServicesMessages.Marshal(b, m, deterministic)
}
func (m *ExposedServicesMessages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExposedServicesMessages.Merge(m, src)
}
func (m *ExposedServicesMessages) XXX_Size() int {
	return xxx_messageInfo_ExposedServicesMessages.Size(m)
}
func (m *ExposedServicesMessages) XXX_DiscardUnknown() {
	xxx_messageInfo_ExposedServicesMessages.DiscardUnknown(m)
}

var xxx_messageInfo_ExposedServicesMessages proto.InternalMessageInfo

func (m *ExposedServicesMessages) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExposedServicesMessages) GetExposedServices() []*ExposedServicesMessages_ExposedService {
	if m != nil {
		return m.ExposedServices
	}
	return nil
}

type ExposedServicesMessages_ExposedService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints            []string `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExposedServicesMessages_ExposedService) Reset() {
	*m = ExposedServicesMessages_ExposedService{}
}
func (m *ExposedServicesMessages_ExposedService) String() string { return proto.CompactTextString(m) }
func (*ExposedServicesMessages_ExposedService) ProtoMessage()    {}
func (*ExposedServicesMessages_ExposedService) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{0, 0}
}

func (m *ExposedServicesMessages_ExposedService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExposedServicesMessages_ExposedService.Unmarshal(m, b)
}
func (m *ExposedServicesMessages_ExposedService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExposedServicesMessages_ExposedService.Marshal(b, m, deterministic)
}
func (m *ExposedServicesMessages_ExposedService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExposedServicesMessages_ExposedService.Merge(m, src)
}
func (m *ExposedServicesMessages_ExposedService) XXX_Size() int {
	return xxx_messageInfo_ExposedServicesMessages_ExposedService.Size(m)
}
func (m *ExposedServicesMessages_ExposedService) XXX_DiscardUnknown() {
	xxx_messageInfo_ExposedServicesMessages_ExposedService.DiscardUnknown(m)
}

var xxx_messageInfo_ExposedServicesMessages_ExposedService proto.InternalMessageInfo

func (m *ExposedServicesMessages_ExposedService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExposedServicesMessages_ExposedService) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func init() {
	proto.RegisterType((*ExposedServicesMessages)(nil), "pb.ExposedServicesMessages")
	proto.RegisterType((*ExposedServicesMessages_ExposedService)(nil), "pb.ExposedServicesMessages.ExposedService")
}

func init() { proto.RegisterFile("discovery.proto", fileDescriptor_1e7ff60feb39c8d0) }

var fileDescriptor_1e7ff60feb39c8d0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0x4b, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0x3a, 0xce, 0xc8, 0x25, 0xee, 0x5a, 0x51, 0x90, 0x5f, 0x9c, 0x9a, 0x12, 0x9c, 0x5a, 0x54, 0x96,
	0x99, 0x9c, 0x5a, 0xec, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x5a, 0x2c, 0x24, 0xc4, 0xc5, 0x92,
	0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0x85, 0x70, 0xf1,
	0xa3, 0x29, 0x97, 0x60, 0x52, 0x60, 0xd6, 0xe0, 0x36, 0xd2, 0xd2, 0x2b, 0x48, 0xd2, 0xc3, 0x61,
	0x12, 0x9a, 0x78, 0x10, 0xba, 0x11, 0x52, 0x4e, 0x5c, 0x7c, 0xa8, 0x42, 0x58, 0xed, 0x96, 0xe1,
	0xe2, 0x4c, 0xcd, 0x4b, 0x29, 0xc8, 0xcf, 0xcc, 0x2b, 0x81, 0xd8, 0xca, 0x19, 0x84, 0x10, 0x30,
	0x4a, 0xe2, 0x62, 0x71, 0x0d, 0x76, 0x09, 0x16, 0x8a, 0xe2, 0x92, 0x40, 0x33, 0xde, 0x05, 0xe6,
	0x6f, 0x21, 0x69, 0x3c, 0x8e, 0x94, 0xc2, 0x27, 0xa9, 0xc4, 0xa0, 0xc1, 0x68, 0xc0, 0x98, 0xc4,
	0x06, 0x0e, 0x38, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xbf, 0xc8, 0xbc, 0x4b, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ESDSClient is the client API for ESDS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ESDSClient interface {
	// list all exported services
	ExposedServicesDiscovery(ctx context.Context, opts ...grpc.CallOption) (ESDS_ExposedServicesDiscoveryClient, error)
}

type eSDSClient struct {
	cc *grpc.ClientConn
}

func NewESDSClient(cc *grpc.ClientConn) ESDSClient {
	return &eSDSClient{cc}
}

func (c *eSDSClient) ExposedServicesDiscovery(ctx context.Context, opts ...grpc.CallOption) (ESDS_ExposedServicesDiscoveryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ESDS_serviceDesc.Streams[0], "/pb.ESDS/ExposedServicesDiscovery", opts...)
	if err != nil {
		return nil, err
	}
	x := &eSDSExposedServicesDiscoveryClient{stream}
	return x, nil
}

type ESDS_ExposedServicesDiscoveryClient interface {
	Send(*ExposedServicesMessages) error
	Recv() (*ExposedServicesMessages, error)
	grpc.ClientStream
}

type eSDSExposedServicesDiscoveryClient struct {
	grpc.ClientStream
}

func (x *eSDSExposedServicesDiscoveryClient) Send(m *ExposedServicesMessages) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eSDSExposedServicesDiscoveryClient) Recv() (*ExposedServicesMessages, error) {
	m := new(ExposedServicesMessages)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ESDSServer is the server API for ESDS service.
type ESDSServer interface {
	// list all exported services
	ExposedServicesDiscovery(ESDS_ExposedServicesDiscoveryServer) error
}

func RegisterESDSServer(s *grpc.Server, srv ESDSServer) {
	s.RegisterService(&_ESDS_serviceDesc, srv)
}

func _ESDS_ExposedServicesDiscovery_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ESDSServer).ExposedServicesDiscovery(&eSDSExposedServicesDiscoveryServer{stream})
}

type ESDS_ExposedServicesDiscoveryServer interface {
	Send(*ExposedServicesMessages) error
	Recv() (*ExposedServicesMessages, error)
	grpc.ServerStream
}

type eSDSExposedServicesDiscoveryServer struct {
	grpc.ServerStream
}

func (x *eSDSExposedServicesDiscoveryServer) Send(m *ExposedServicesMessages) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eSDSExposedServicesDiscoveryServer) Recv() (*ExposedServicesMessages, error) {
	m := new(ExposedServicesMessages)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ESDS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ESDS",
	HandlerType: (*ESDSServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExposedServicesDiscovery",
			Handler:       _ESDS_ExposedServicesDiscovery_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "discovery.proto",
}
