// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type ExposedServicesRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExposedServicesRequest) Reset()         { *m = ExposedServicesRequest{} }
func (m *ExposedServicesRequest) String() string { return proto.CompactTextString(m) }
func (*ExposedServicesRequest) ProtoMessage()    {}
func (*ExposedServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{0}
}

func (m *ExposedServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExposedServicesRequest.Unmarshal(m, b)
}
func (m *ExposedServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExposedServicesRequest.Marshal(b, m, deterministic)
}
func (m *ExposedServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExposedServicesRequest.Merge(m, src)
}
func (m *ExposedServicesRequest) XXX_Size() int {
	return xxx_messageInfo_ExposedServicesRequest.Size(m)
}
func (m *ExposedServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExposedServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExposedServicesRequest proto.InternalMessageInfo

func (m *ExposedServicesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type ExposedServicesReply struct {
	Name                 string                                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ExposedServices      []*ExposedServicesReply_ExposedService `protobuf:"bytes,2,rep,name=ExposedServices,proto3" json:"ExposedServices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ExposedServicesReply) Reset()         { *m = ExposedServicesReply{} }
func (m *ExposedServicesReply) String() string { return proto.CompactTextString(m) }
func (*ExposedServicesReply) ProtoMessage()    {}
func (*ExposedServicesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{1}
}

func (m *ExposedServicesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExposedServicesReply.Unmarshal(m, b)
}
func (m *ExposedServicesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExposedServicesReply.Marshal(b, m, deterministic)
}
func (m *ExposedServicesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExposedServicesReply.Merge(m, src)
}
func (m *ExposedServicesReply) XXX_Size() int {
	return xxx_messageInfo_ExposedServicesReply.Size(m)
}
func (m *ExposedServicesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ExposedServicesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ExposedServicesReply proto.InternalMessageInfo

func (m *ExposedServicesReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExposedServicesReply) GetExposedServices() []*ExposedServicesReply_ExposedService {
	if m != nil {
		return m.ExposedServices
	}
	return nil
}

type ExposedServicesReply_ExposedService struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints            []string `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExposedServicesReply_ExposedService) Reset()         { *m = ExposedServicesReply_ExposedService{} }
func (m *ExposedServicesReply_ExposedService) String() string { return proto.CompactTextString(m) }
func (*ExposedServicesReply_ExposedService) ProtoMessage()    {}
func (*ExposedServicesReply_ExposedService) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ff60feb39c8d0, []int{1, 0}
}

func (m *ExposedServicesReply_ExposedService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExposedServicesReply_ExposedService.Unmarshal(m, b)
}
func (m *ExposedServicesReply_ExposedService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExposedServicesReply_ExposedService.Marshal(b, m, deterministic)
}
func (m *ExposedServicesReply_ExposedService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExposedServicesReply_ExposedService.Merge(m, src)
}
func (m *ExposedServicesReply_ExposedService) XXX_Size() int {
	return xxx_messageInfo_ExposedServicesReply_ExposedService.Size(m)
}
func (m *ExposedServicesReply_ExposedService) XXX_DiscardUnknown() {
	xxx_messageInfo_ExposedServicesReply_ExposedService.DiscardUnknown(m)
}

var xxx_messageInfo_ExposedServicesReply_ExposedService proto.InternalMessageInfo

func (m *ExposedServicesReply_ExposedService) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExposedServicesReply_ExposedService) GetEndpoints() []string {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func init() {
	proto.RegisterType((*ExposedServicesRequest)(nil), "pb.ExposedServicesRequest")
	proto.RegisterType((*ExposedServicesReply)(nil), "pb.ExposedServicesReply")
	proto.RegisterType((*ExposedServicesReply_ExposedService)(nil), "pb.ExposedServicesReply.ExposedService")
}

func init() { proto.RegisterFile("discovery.proto", fileDescriptor_1e7ff60feb39c8d0) }

var fileDescriptor_1e7ff60feb39c8d0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0x4b, 0x2d, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52,
	0xd2, 0xe1, 0x12, 0x73, 0xad, 0x28, 0xc8, 0x2f, 0x4e, 0x4d, 0x09, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0x2d, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x0e, 0x32, 0x72, 0x89, 0x60,
	0x28, 0x2f, 0xc8, 0xa9, 0xc4, 0xa6, 0x58, 0x28, 0x90, 0x8b, 0x1f, 0x4d, 0xad, 0x04, 0x93, 0x02,
	0xb3, 0x06, 0xb7, 0x91, 0xba, 0x5e, 0x41, 0x92, 0x1e, 0x36, 0x63, 0xd0, 0x04, 0x83, 0xd0, 0xf5,
	0x4b, 0x39, 0x71, 0xf1, 0xa1, 0x0a, 0x61, 0xb5, 0x58, 0x86, 0x8b, 0x33, 0x35, 0x2f, 0xa5, 0x20,
	0x3f, 0x33, 0xaf, 0x04, 0x62, 0x25, 0x67, 0x10, 0x42, 0xc0, 0x28, 0x8a, 0x8b, 0xc5, 0x35, 0xd8,
	0x25, 0x58, 0x28, 0x88, 0x4b, 0x02, 0xcd, 0x78, 0x17, 0x58, 0xf8, 0x08, 0x49, 0x61, 0x75, 0x21,
	0x38, 0x5c, 0xa4, 0x24, 0x70, 0xb9, 0x5e, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0xb0, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x09, 0xf7, 0x52, 0x50, 0x6b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ESDSClient is the client API for ESDS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ESDSClient interface {
	// list all exported services
	ExposedServicesDiscovery(ctx context.Context, in *ExposedServicesRequest, opts ...grpc.CallOption) (*ExposedServicesReply, error)
}

type eSDSClient struct {
	cc *grpc.ClientConn
}

func NewESDSClient(cc *grpc.ClientConn) ESDSClient {
	return &eSDSClient{cc}
}

func (c *eSDSClient) ExposedServicesDiscovery(ctx context.Context, in *ExposedServicesRequest, opts ...grpc.CallOption) (*ExposedServicesReply, error) {
	out := new(ExposedServicesReply)
	err := c.cc.Invoke(ctx, "/pb.ESDS/ExposedServicesDiscovery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ESDSServer is the server API for ESDS service.
type ESDSServer interface {
	// list all exported services
	ExposedServicesDiscovery(context.Context, *ExposedServicesRequest) (*ExposedServicesReply, error)
}

func RegisterESDSServer(s *grpc.Server, srv ESDSServer) {
	s.RegisterService(&_ESDS_serviceDesc, srv)
}

func _ESDS_ExposedServicesDiscovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExposedServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ESDSServer).ExposedServicesDiscovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ESDS/ExposedServicesDiscovery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ESDSServer).ExposedServicesDiscovery(ctx, req.(*ExposedServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ESDS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ESDS",
	HandlerType: (*ESDSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExposedServicesDiscovery",
			Handler:    _ESDS_ExposedServicesDiscovery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discovery.proto",
}
