apiVersion: mm.ibm.istio.io/v1
kind: ServiceBinding
metadata:
  name: helloworld
spec:
  name: helloworld
  namespace: default
  mesh_fed_config_selector:
    fed-config: passthrough
  alias: helloworldyall
  endpoints:
  - "9.1.2.3:5000"
  port: 5000
  # optional
  # subset: v2
