
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mm.ibm.istio.io
  resources:
  - meshfeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mm.ibm.istio.io
  resources:
  - meshfeds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mm.ibm.istio.io
  resources:
  - servicebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mm.ibm.istio.io
  resources:
  - servicebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mm.ibm.istio.io
  resources:
  - serviceexpositions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mm.ibm.istio.io
  resources:
  - serviceexpositions/status
  verbs:
  - get
  - patch
  - update
