apiVersion: mm.ibm.istio.io/v1
kind: MeshFedConfig
metadata:
  name: limited-trust
  namespace: limited-trust
  labels:
    secret: cluster1
    fed-config: limited-trust
spec:
  tls_context_selector:
    mesh: limited-trust
    secret: cluster1
  use_egress_gateway: true
  egress_gateway_selector:
    istio: egressgateway
  egress_gateway_port: 443
  use_ingress_gateway: true
  ingress_gateway_selector:
    istio: ingressgateway
  ingress_gateway_port: 15443
