apiVersion: mm.ibm.istio.io/v1
kind: MeshFedConfig
metadata:
  name: limited-trust
spec:
  # TODO What is this?
  tls_context_selector:
    foo: bar
  use_egress_gateway: true
  egress_gateway_selector:
    istio: egressgateway
  egress_gateway_port: 10001
  use_ingress_gateway: true
  ingress_gateway_selector:
    istio: ingressgateway
  ingress_gateway_port: 15443
